language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U setuptools
  - pip install -U pytest
  - pip install pytest-cov
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install -e ".[test]"
script:
  - pytest --cov=dr_scaffold/ tests/ # run tests
after_success:
  - codecov # submit coverage
notifications:
  email: false
